'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,List,ChevronLeft,ChevronRight,Heart} from 'lucide-react';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import story from './story.json';

type Turn={from:number;to:number;direction:1|-1};
export default function Home(){
 const [page,setPage]=useState(0); const [narrow,setNarrow]=useState(false); const [turn,setTurn]=useState<Turn|null>(null);
 const [contents,setContents]=useState(false); const [jump,setJump]=useState('1'); const [error,setError]=useState('');
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null); const touch=useRef<{x:number;y:number}|null>(null);const readRef=useRef<HTMLElement|null>(null);
 const pageRef=useRef(0); const busy=useRef(false);
 useEffect(()=>{const mq=window.matchMedia('(max-width:760px)');const update=()=>{setNarrow(mq.matches);setTurn(null);busy.current=false;if(timer.current)clearTimeout(timer.current);setPage(p=>mq.matches?p:p===0?0:p%2===0?p-1:p);};update();mq.addEventListener('change',update);return()=>{mq.removeEventListener('change',update);if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{pageRef.current=page;setJump(String(page||1));},[page]);
 const go=useCallback((requested:number,animate=true)=>{
  if(!Number.isInteger(requested)||requested<0||requested>200||busy.current)return;
  const target=requested===0?0:narrow?requested:requested%2===0?requested-1:requested;
  const old=pageRef.current;if(old===target)return;setError('');setContents(false);
  if(animate&&old>0&&target>0&&!window.matchMedia('(prefers-reduced-motion:reduce)').matches){busy.current=true;setTurn({from:old,to:target,direction:target>old?1:-1});timer.current=setTimeout(()=>{setTurn(null);busy.current=false;},650);}
  pageRef.current=target;setPage(target);
  window.requestAnimationFrame(()=>{readRef.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});});
 },[narrow]);
 const next=useCallback(()=>{const p=pageRef.current;go(p===0?1:Math.min(narrow?200:199,p+(narrow?1:2)));},[go,narrow]);
 const previous=useCallback(()=>{const p=pageRef.current;go(p<=(narrow?1:2)?0:p-(narrow?1:2));},[go,narrow]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(contents||event.altKey||event.ctrlKey||event.metaKey||/INPUT|TEXTAREA|SELECT/.test((event.target as HTMLElement)?.tagName)||((event.target as HTMLElement)?.isContentEditable))return;if(event.key==='ArrowRight'){event.preventDefault();next();}if(event.key==='ArrowLeft'){event.preventDefault();previous();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[next,previous,contents]);
 const end=narrow?page:Math.min(page+1,200);const chapter=story.chapters[Math.floor(Math.max(0,page-1)/10)];
 const pageContent=(number:number)=>{const p=story.pages[number-1];if(!p)return null;const first=(number-1)%10===0;return <><div className="running-head"><span>{number%2===1?'BEFORE I KNEW YOUR NAME':p.title}</span><span aria-hidden="true">✦</span></div><div className={`page-writing ${first?'chapter-start':''}`}>{first&&<div className="chapter-heading"><span>CHAPTER {String(p.chapter).padStart(2,'0')}</span><h2>{p.title}</h2><div className="chapter-rule"/></div>}<div className="story-text">{p.text.split('\n\n').map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div>{number===200&&<div className="fin">The end <Heart size={14}/></div>}</div><div className="folio"><span aria-hidden="true">—</span> {number} <span aria-hidden="true">—</span></div></>;};
 return <main className={`library ${page?'is-reading':''}`}>
  <header className="masthead"><button className="wordmark" onClick={()=>go(0,false)} aria-label="Return to book cover">a little forever<span>THE SHREYA EDITION</span></button>{page>0?<div className="header-actions"><button className="quiet-button" onClick={()=>go(0,false)}><BookOpen size={17}/><span>Cover</span></button><Sheet open={contents} onOpenChange={setContents}><SheetTrigger className="quiet-button"><List size={18}/><span>Chapters</span></SheetTrigger><SheetContent className="contents-panel"><SheetHeader><SheetTitle className="contents-title">Between the pages</SheetTitle><SheetDescription>20 chapters · Shreya’s story</SheetDescription></SheetHeader><nav className="chapter-list" aria-label="Chapters">{story.chapters.map(c=><button key={c.number} className={chapter.number===c.number?'selected':''} onClick={()=>go(c.page,false)} aria-current={chapter.number===c.number?'location':undefined}><span className="chapter-index">{String(c.number).padStart(2,'0')}</span><span>{c.title}</span><span className="chapter-page">{c.page}</span></button>)}</nav></SheetContent></Sheet></div>:<span className="edition">A story in 200 pages</span>}</header>
  {page===0?<div className="cover-stage"><div className="cover-intro"><span className="eyebrow">FOR THE HOPELESS ROMANTIC</span><h1>Some stories start<br/>before you know<br/><em>their name.</em></h1><p>A little English. Konjam Tamil.<br/>And a heart that never saw it coming.</p><button className="primary" onClick={()=>go(1)}><BookOpen size={18}/>Open the book<ArrowRight size={18}/></button><div className="cover-meta">20 chapters <span>·</span> 200 story pages</div></div><button className="closed-book" onClick={()=>go(1)} aria-label="Open Before I Knew Your Name"><img src="/cover.jpg" alt="The photograph supplied for Shreya’s book cover"/><div className="cover-shade"/><div className="cover-type"><span>A LITTLE FOREVER</span><h2>Before I Knew<br/><i>Your Name</i></h2><p>Shreya’s story</p></div><div className="cover-bottom">ONE YEAR APART.<br/>A WHOLE STORY BETWEEN.</div></button></div>:<section className="reader" ref={readRef} tabIndex={-1} aria-label="Book reader">
   <div className="reader-heading"><span>CHAPTER {String(chapter.number).padStart(2,'0')} <span className="heading-dot">/</span> {chapter.title}</span><span className="reading-count" aria-live="polite" aria-atomic="true">{narrow?`Page ${page}`:`Pages ${page}–${end}`} of 200</span></div>
   <div className={`book-scene ${turn?'turning':''}`} onTouchStart={e=>{touch.current={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x;const dy=e.changedTouches[0].clientY-touch.current.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5){if(dx<0)next();else previous();}touch.current=null;}}>
    <div className="open-book"><article className="paper left-paper" aria-label={`Page ${page}`}>{pageContent(page)}</article>{!narrow&&<article className="paper right-paper" aria-label={`Page ${end}`}>{pageContent(end)}</article>}
    {!narrow&&turn&&<><div className={`turn-under paper ${turn.direction===1?'left-paper':'right-paper'}`} aria-hidden="true">{pageContent(turn.direction===1?turn.from:turn.from+1)}</div><div className={`flipping-leaf ${turn.direction===1?'forward':'backward'}`} aria-hidden="true"><div className="leaf-face paper">{pageContent(turn.direction===1?turn.from+1:turn.from)}</div><div className="leaf-face leaf-back paper">{pageContent(turn.direction===1?turn.to:turn.to+1)}</div></div></>}
    </div>
   </div>
   <div className="reader-controls"><Pagination aria-label="Book pages"><PaginationContent className="book-navigation"><PaginationItem><button className="turn-button" onClick={previous} disabled={!!turn} aria-label={page===1?'Return to cover':'Previous page'}><ChevronLeft size={18}/><span>Previous</span></button></PaginationItem><PaginationItem><form className="jump-form" onSubmit={e=>{e.preventDefault();const requested=Number(jump);if(!Number.isInteger(requested)||requested<1||requested>200){setError('Choose a page from 1 to 200.');return;}go(requested);}}><label htmlFor="page-number">Page</label><input id="page-number" aria-describedby={error?'page-error':undefined} aria-invalid={!!error} value={jump} onChange={e=>setJump(e.target.value)} type="number" min="1" max="200" inputMode="numeric"/><button type="submit" aria-label="Go to page"><ArrowRight size={16}/></button></form></PaginationItem><PaginationItem><button className="turn-button" onClick={next} disabled={end===200||!!turn} aria-label="Next page"><span>Next</span><ChevronRight size={18}/></button></PaginationItem></PaginationContent></Pagination></div>
   {error&&<p id="page-error" role="alert" className="page-error">{error}</p>}<div className="reading-progress" aria-hidden="true"><span style={{width:`${end/2}%`}}/></div><p className="reader-hint">{narrow?'Swipe or tap to turn the page':'Use the arrow keys, or turn a page below'}{end===200&&<span className="end-note"> · Thank you for reading Shreya’s story.</span>}</p>
  </section>}
  <footer className="site-footer"><span>{page?'An original work of fiction.':'A love story, with a few wrong turns.'}</span><span>Made for someone special ♡</span></footer>
 </main>;
}
